// All countries
// length 252
const countries = {
    AF: { name: "Afghanistan", currency: "AFN" },
    AX: { name: "Åland Islands", currency: "EUR" },
    AL: { name: "Albania", currency: "ALL" },
    DZ: { name: "Algeria", currency: "DZD" },
    AD: { name: "Andorra", currency: "EUR" },
    AO: { name: "Angola", currency: "AOA" },
    AI: { name: "Anguilla", currency: "XCD" },
    AQ: { name: "Antarctica", currency: "AAD" },
    AG: { name: "Antigua & Barbuda", currency: "XCD" },
    AR: { name: "Argentina", currency: "ARS" },
    AM: { name: "Armenia", currency: "AMD" },
    AW: { name: "Aruba", currency: "AWG" },
    AU: { name: "Australia", currency: "AUD" },
    AT: { name: "Austria", currency: "EUR" },
    AZ: { name: "Azerbaijan", currency: "AZN" },
    BS: { name: "Bahamas", currency: "BSD" },
    BH: { name: "Bahrain", currency: "BHD" },
    BD: { name: "Bangladesh", currency: "BDT" },
    BB: { name: "Barbados", currency: "BBD" },
    BY: { name: "Belarus", currency: "BYN" },
    BE: { name: "Belgium", currency: "EUR" },
    BZ: { name: "Belize", currency: "BZD" },
    BJ: { name: "Benin", currency: "XOF" },
    BM: { name: "Bermuda", currency: "BMD" },
    BT: { name: "Bhutan", currency: "BTN" },
    BO: { name: "Bolivia", currency: "BOB" },
    BA: { name: "Bosnia & Herzegovina", currency: "BAM" },
    BW: { name: "Botswana", currency: "BWP" },
    BV: { name: "Bouvet Island", currency: "NOK" },
    BR: { name: "Brazil", currency: "BRL" },
    BN: { name: "Brunei", currency: "BND" },
    BG: { name: "Bulgaria", currency: "BGN" },
    BF: { name: "Burkina Faso", currency: "XOF" },
    BI: { name: "Burundi", currency: "BIF" },
    KH: { name: "Cambodia", currency: "KHR" },
    CM: { name: "Cameroon", currency: "XAF" },
    CA: { name: "Canada", currency: "CAD" },
    CV: { name: "Cape Verde", currency: "CVE" },
    KY: { name: "Cayman Islands", currency: "KYD" },
    CF: { name: "Central African Republic", currency: "XAF" },
    TD: { name: "Chad", currency: "XAF" },
    CL: { name: "Chile", currency: "CLP" },
    CN: { name: "China", currency: "CNY" },
    CX: { name: "Christmas Island", currency: "AUD" },
    CC: { name: "Cocos (Keeling) Islands", currency: "AUD" },
    CO: { name: "Colombia", currency: "COP" },
    KM: { name: "Comoros", currency: "KMF" },
    CG: { name: "Congo - Brazzaville", currency: "XAF" },
    CD: { name: "Congo - Kinshasa", currency: "CDF" },
    CK: { name: "Cook Islands", currency: "NZD" },
    CR: { name: "Costa Rica", currency: "CRC" },
    CI: { name: "Côte d’Ivoire", currency: "XOF" },
    HR: { name: "Croatia", currency: "HRK" },
    CU: { name: "Cuba", currency: "CUP" },
    CW: { name: "Curaçao", currency: "ANG" },
    CY: { name: "Cyprus", currency: "EUR" },
    CZ: { name: "Czechia", currency: "CZK" },
    DK: { name: "Denmark", currency: "DKK" },
    DJ: { name: "Djibouti", currency: "DJF" },
    DM: { name: "Dominica", currency: "XCD" },
    DO: { name: "Dominican Republic", currency: "DOP" },
    EG: { name: "Egypt", currency: "EGP" },
    GQ: { name: "Equatorial Guinea", currency: "XAF" },
    ER: { name: "Eritrea", currency: "ERN" },
    EE: { name: "Estonia", currency: "EUR" },
    ET: { name: "Ethiopia", currency: "ETB" },
    FK: { name: "Falkland Islands (Islas Malvinas)", currency: "FKP" },
    FO: { name: "Faroe Islands", currency: "DKK" },
    FJ: { name: "Fiji", currency: "FJD" },
    FI: { name: "Finland", currency: "EUR" },
    FR: { name: "France", currency: "EUR" },
    GF: { name: "French Guiana", currency: "EUR" },
    PF: { name: "French Polynesia", currency: "XPF" },
    TF: { name: "French Southern Territories", currency: "EUR" },
    GA: { name: "Gabon", currency: "XAF" },
    GM: { name: "Gambia", currency: "GMD" },
    GE: { name: "Georgia", currency: "GEL" },
    DE: { name: "Germany", currency: "EUR" },
    GH: { name: "Ghana", currency: "GHS" },
    GI: { name: "Gibraltar", currency: "GIP" },
    GR: { name: "Greece", currency: "EUR" },
    GL: { name: "Greenland", currency: "DKK" },
    GD: { name: "Grenada", currency: "XCD" },
    GP: { name: "Guadeloupe", currency: "EUR" },
    GT: { name: "Guatemala", currency: "GTQ" },
    GG: { name: "Guernsey", currency: "GBP" },
    GN: { name: "Guinea", currency: "GNF" },
    GW: { name: "Guinea-Bissau", currency: "XOF" },
    GY: { name: "Guyana", currency: "GYD" },
    HT: { name: "Haiti", currency: "HTG" },
    HM: { name: "Heard & McDonald Islands", currency: "AUD" },
    VA: { name: "Vatican City", currency: "EUR" },
    HN: { name: "Honduras", currency: "HNL" },
    HK: { name: "Hong Kong", currency: "HKD" },
    HU: { name: "Hungary", currency: "HUF" },
    IS: { name: "Iceland", currency: "ISK" },
    IN: { name: "India", currency: "INR" },
    ID: { name: "Indonesia", currency: "IDR" },
    IR: { name: "Iran", currency: "IRR" },
    IQ: { name: "Iraq", currency: "IQD" },
    IE: { name: "Ireland", currency: "EUR" },
    IM: { name: "Isle of Man", currency: "GBP" },
    IT: { name: "Italy", currency: "EUR" },
    JM: { name: "Jamaica", currency: "JMD" },
    JP: { name: "Japan", currency: "JPY" },
    JE: { name: "Jersey", currency: "GBP" },
    JO: { name: "Jordan", currency: "JOD" },
    KZ: { name: "Kazakhstan", currency: "KZT" },
    KE: { name: "Kenya", currency: "KES" },
    KI: { name: "Kiribati", currency: "AUD" },
    KP: { name: "North Korea", currency: "KPW" },
    KR: { name: "South Korea", currency: "KRW" },
    XK: { name: "Kosovo", currency: "EUR" },
    KW: { name: "Kuwait", currency: "KWD" },
    KG: { name: "Kyrgyzstan", currency: "KGS" },
    LA: { name: "Laos", currency: "LAK" },
    LV: { name: "Latvia", currency: "EUR" },
    LB: { name: "Lebanon", currency: "LBP" },
    LS: { name: "Lesotho", currency: "LSL" },
    LR: { name: "Liberia", currency: "LRD" },
    LY: { name: "Libya", currency: "LYD" },
    LI: { name: "Liechtenstein", currency: "CHF" },
    LT: { name: "Lithuania", currency: "EUR" },
    LU: { name: "Luxembourg", currency: "EUR" },
    MO: { name: "Macao", currency: "MOP" },
    MK: { name: "North Macedonia", currency: "MKD" },
    MG: { name: "Madagascar", currency: "MGA" },
    MW: { name: "Malawi", currency: "MWK" },
    MY: { name: "Malaysia", currency: "MYR" },
    MV: { name: "Maldives", currency: "MVR" },
    ML: { name: "Mali", currency: "XOF" },
    MT: { name: "Malta", currency: "EUR" },
    MQ: { name: "Martinique", currency: "EUR" },
    MR: { name: "Mauritania", currency: "MRO" },
    MU: { name: "Mauritius", currency: "MUR" },
    YT: { name: "Mayotte", currency: "EUR" },
    MX: { name: "Mexico", currency: "MXN" },
    MD: { name: "Moldova", currency: "MDL" },
    MC: { name: "Monaco", currency: "EUR" },
    MN: { name: "Mongolia", currency: "MNT" },
    ME: { name: "Montenegro", currency: "EUR" },
    MS: { name: "Montserrat", currency: "XCD" },
    MA: { name: "Morocco", currency: "MAD" },
    MZ: { name: "Mozambique", currency: "MZN" },
    MM: { name: "Myanmar (Burma)", currency: "MMK" },
    NA: { name: "Namibia", currency: "NAD" },
    NR: { name: "Nauru", currency: "AUD" },
    NP: { name: "Nepal", currency: "NPR" },
    NL: { name: "Netherlands", currency: "EUR" },
    AN: { name: "Curaçao", currency: "ANG" },
    NC: { name: "New Caledonia", currency: "XPF" },
    NZ: { name: "New Zealand", currency: "NZD" },
    NI: { name: "Nicaragua", currency: "NIO" },
    NE: { name: "Niger", currency: "XOF" },
    NG: { name: "Nigeria", currency: "NGN" },
    NU: { name: "Niue", currency: "NZD" },
    NF: { name: "Norfolk Island", currency: "AUD" },
    NO: { name: "Norway", currency: "NOK" },
    OM: { name: "Oman", currency: "OMR" },
    PK: { name: "Pakistan", currency: "PKR" },
    PS: { name: "Palestine", currency: "ILS" },
    PA: { name: "Panama", currency: "PAB" },
    PG: { name: "Papua New Guinea", currency: "PGK" },
    PY: { name: "Paraguay", currency: "PYG" },
    PE: { name: "Peru", currency: "PEN" },
    PH: { name: "Philippines", currency: "PHP" },
    PN: { name: "Pitcairn Islands", currency: "NZD" },
    PL: { name: "Poland", currency: "PLN" },
    PT: { name: "Portugal", currency: "EUR" },
    QA: { name: "Qatar", currency: "QAR" },
    RE: { name: "Réunion", currency: "EUR" },
    RO: { name: "Romania", currency: "RON" },
    RU: { name: "Russia", currency: "RUB" },
    RW: { name: "Rwanda", currency: "RWF" },
    BL: { name: "St. Barthélemy", currency: "EUR" },
    SH: { name: "St. Helena", currency: "SHP" },
    KN: { name: "St. Kitts & Nevis", currency: "XCD" },
    LC: { name: "St. Lucia", currency: "XCD" },
    MF: { name: "St. Martin", currency: "EUR" },
    PM: { name: "St. Pierre & Miquelon", currency: "EUR" },
    VC: { name: "St. Vincent & Grenadines", currency: "XCD" },
    WS: { name: "Samoa", currency: "WST" },
    SM: { name: "San Marino", currency: "EUR" },
    ST: { name: "São Tomé & Príncipe", currency: "STD" },
    SA: { name: "Saudi Arabia", currency: "SAR" },
    SN: { name: "Senegal", currency: "XOF" },
    RS: { name: "Serbia", currency: "RSD" },
    CS: { name: "Serbia", currency: "RSD" },
    SC: { name: "Seychelles", currency: "SCR" },
    SL: { name: "Sierra Leone", currency: "SLL" },
    SG: { name: "Singapore", currency: "SGD" },
    SX: { name: "Sint Maarten", currency: "ANG" },
    SK: { name: "Slovakia", currency: "EUR" },
    SI: { name: "Slovenia", currency: "EUR" },
    SB: { name: "Solomon Islands", currency: "SBD" },
    SO: { name: "Somalia", currency: "SOS" },
    ZA: { name: "South Africa", currency: "ZAR" },
    GS: { name: "South Georgia & South Sandwich Islands", currency: "GBP" },
    SS: { name: "South Sudan", currency: "SSP" },
    ES: { name: "Spain", currency: "EUR" },
    LK: { name: "Sri Lanka", currency: "LKR" },
    SD: { name: "Sudan", currency: "SDG" },
    SR: { name: "Suriname", currency: "SRD" },
    SJ: { name: "Svalbard & Jan Mayen", currency: "NOK" },
    SZ: { name: "Eswatini", currency: "SZL" },
    SE: { name: "Sweden", currency: "SEK" },
    CH: { name: "Switzerland", currency: "CHF" },
    SY: { name: "Syria", currency: "SYP" },
    TW: { name: "Taiwan", currency: "TWD" },
    TJ: { name: "Tajikistan", currency: "TJS" },
    TZ: { name: "Tanzania", currency: "TZS" },
    TH: { name: "Thailand", currency: "THB" },
    TG: { name: "Togo", currency: "XOF" },
    TK: { name: "Tokelau", currency: "NZD" },
    TO: { name: "Tonga", currency: "TOP" },
    TT: { name: "Trinidad & Tobago", currency: "TTD" },
    TN: { name: "Tunisia", currency: "TND" },
    TR: { name: "Turkey", currency: "TRY" },
    TM: { name: "Turkmenistan", currency: "TMT" },
    TV: { name: "Tuvalu", currency: "AUD" },
    UG: { name: "Uganda", currency: "UGX" },
    UA: { name: "Ukraine", currency: "UAH" },
    AE: { name: "United Arab Emirates", currency: "AED" },
    GB: { name: "United Kingdom", currency: "GBP" },
    US: { name: "United States", currency: "USD" },
    UY: { name: "Uruguay", currency: "UYU" },
    UZ: { name: "Uzbekistan", currency: "UZS" },
    VU: { name: "Vanuatu", currency: "VUV" },
    VE: { name: "Venezuela", currency: "VEF" },
    VN: { name: "Vietnam", currency: "VND" },
    WF: { name: "Wallis & Futuna", currency: "XPF" },
    EH: { name: "Western Sahara", currency: "MAD" },
    YE: { name: "Yemen", currency: "YER" },
    ZM: { name: "Zambia", currency: "ZMW" },
    ZW: { name: "Zimbabwe", currency: "ZWL" }
};


// let country_code = {
//     "AED": "AE",
//     "AFN": "AF",
//     "XCD": "AG",
//     "ALL": "AL",
//     "AMD": "AM",
//     "ANG": "AN",
//     "AOA": "AO",
//     "AQD": "AQ",
//     "ARS": "AR",
//     "AUD": "AU",
//     "AZN": "AZ",
//     "BAM": "BA",
//     "BBD": "BB",
//     "BDT": "BD",
//     "XOF": "BE",
//     "BGN": "BG",
//     "BHD": "BH",
//     "BIF": "BI",
//     "BMD": "BM",
//     "BND": "BN",
//     "BOB": "BO",
//     "BRL": "BR",
//     "BSD": "BS",
//     "NOK": "BV",
//     "BWP": "BW",
//     "BYR": "BY",
//     "BZD": "BZ",
//     "CAD": "CA",
//     "CDF": "CD",
//     "XAF": "CF",
//     "CHF": "CH",
//     "CLP": "CL",
//     "CNY": "CN",
//     "COP": "CO",
//     "CRC": "CR",
//     "CUP": "CU",
//     "CVE": "CV",
//     "CYP": "CY",
//     "CZK": "CZ",
//     "DJF": "DJ",
//     "DKK": "DK",
//     "DOP": "DO",
//     "DZD": "DZ",
//     "ECS": "EC",
//     "EEK": "EE",
//     "EGP": "EG",
//     "ETB": "ET",
//     "EUR": "FR",
//     "FJD": "FJ",
//     "FKP": "FK",
//     "GBP": "GB",
//     "GEL": "GE",
//     "GGP": "GG",
//     "GHS": "GH",
//     "GIP": "GI",
//     "GMD": "GM",
//     "GNF": "GN",
//     "GTQ": "GT",
//     "GYD": "GY",
//     "HKD": "HK",
//     "HNL": "HN",
//     "HRK": "HR",
//     "HTG": "HT",
//     "HUF": "HU",
//     "IDR": "ID",
//     "ILS": "IL",
//     "INR": "IN",
//     "IQD": "IQ",
//     "IRR": "IR",
//     "ISK": "IS",
//     "JMD": "JM",
//     "JOD": "JO",
//     "JPY": "JP",
//     "KES": "KE",
//     "KGS": "KG",
//     "KHR": "KH",
//     "KMF": "KM",
//     "KPW": "KP",
//     "KRW": "KR",
//     "KWD": "KW",
//     "KYD": "KY",
//     "KZT": "KZ",
//     "LAK": "LA",
//     "LBP": "LB",
//     "LKR": "LK",
//     "LRD": "LR",
//     "LSL": "LS",
//     "LTL": "LT",
//     "LVL": "LV",
//     "LYD": "LY",
//     "MAD": "MA",
//     "MDL": "MD",
//     "MGA": "MG",
//     "MKD": "MK",
//     "MMK": "MM",
//     "MNT": "MN",
//     "MOP": "MO",
//     "MRO": "MR",
//     "MTL": "MT",
//     "MUR": "MU",
//     "MVR": "MV",
//     "MWK": "MW",
//     "MXN": "MX",
//     "MYR": "MY",
//     "MZN": "MZ",
//     "NAD": "NA",
//     "XPF": "NC",
//     "NGN": "NG",
//     "NIO": "NI",
//     "NPR": "NP",
//     "NZD": "NZ",
//     "OMR": "OM",
//     "PAB": "PA",
//     "PEN": "PE",
//     "PGK": "PG",
//     "PHP": "PH",
//     "PKR": "PK",
//     "PLN": "PL",
//     "PYG": "PY",
//     "QAR": "QA",
//     "RON": "RO",
//     "RSD": "RS",
//     "RUB": "RU",
//     "RWF": "RW",
//     "SAR": "SA",
//     "SBD": "SB",
//     "SCR": "SC",
//     "SDG": "SD",
//     "SEK": "SE",
//     "SGD": "SG",
//     "SKK": "SK",
//     "SLL": "SL",
//     "SOS": "SO",
//     "SRD": "SR",
//     "STD": "ST",
//     "SVC": "SV",
//     "SYP": "SY",
//     "SZL": "SZ",
//     "THB": "TH",
//     "TJS": "TJ",
//     "TMT": "TM",
//     "TND": "TN",
//     "TOP": "TO",
//     "TRY": "TR",
//     "TTD": "TT",
//     "TWD": "TW",
//     "TZS": "TZ",
//     "UAH": "UA",
//     "UGX": "UG",
//     "USD": "US",
//     "UYU": "UY",
//     "UZS": "UZ",
//     "VEF": "VE",
//     "VND": "VN",
//     "VUV": "VU",
//     "YER": "YE",
//     "ZAR": "ZA",
//     "ZMK": "ZM",
//     "ZWD": "ZW"
//   }